federation_version: =2.8.1

subgraphs:
  ~ronseg-hacsym:
    routing_url: http://localhost:4001/channel/graphql
    schema:
      file: ./channel/schema.graphql
  ~zod:
    routing_url: http://localhost:4002/channel/graphql
    schema:
      file: ./channel/schema.graphql
